<?php
/**
 * Created by PhpStorm.
 * User: 49396
 * Date: 2019/2/21
 * Time: 20:37
 *
 */

class work_deQueue extends Thread
{
    public function __construct(){
        $this->start();
    }
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $redis = new Redis();
        $redis->connect('127.0.0.1', 6379);
        /*如果size=0，就等待其他线程notify*/
        if($redis->dbSize()==0){
            try {
                $this->wait();
            }catch (Exception $e) {
                var_dump($e->getMessage());
            }
        }
        $this->outQueue($redis);



    }
    public function outQueue($redis){
        /*取出订阅的信息*/

        $email = $redis->RPOP("email");
        $email_proxy=new send_email();
        $email_proxy->sendemail($email);
    }
}